name: lc
channels:
  - conda-forge
dependencies:
  - cmake=3.27.9
  - llvmdev=16.0.6
  - clangdev=16.0.6
  - compilers=1.7.0
  - make=4.3
  - zlib=1.2.13
  - git=2.43.0
  - python=3.12.0
  - toml=0.10.2
  - xtensor=0.24.7
  - bison=3.4
  - re2c=3.1
