name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main


jobs:
  Build:
    name: LFortran CI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: mamba-org/provision-with-micromamba@main
        if: contains(matrix.os, 'ubuntu')
        with:
          environment-file: environment_unix.yml

      - uses: mamba-org/provision-with-micromamba@main
        if: contains(matrix.os, 'macos')
        with:
          environment-file: environment_macos.yml

      - uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Build (Linux / macOS)
        shell: bash -l {0}
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
            ./build.sh
            export PATH=$CONDA_PREFIX/bin:$PATH

      - name: Test (Linux / macOS)
        shell: bash -l -e {0}
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
            lc --ast-dump tests/test.cpp
            lc --extra-arg=-Isrc/runtime/include examples/expr2.c --asr-dump
            ./run_tests.py

      - name: Test2 (Linux / macOS)
        shell: bash -l -e {0}
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
            which clang

            lc examples/expr2.c --backend c --extra-arg="-Isrc/runtime/include" --

            lc examples/expr2.c --backend wasm --extra-arg="-Isrc/runtime/include" --

            lc examples/expr2.c --backend llvm --extra-arg="-Isrc/runtime/include" --

            lc tests/array_01.cpp --backend=llvm --extra-arg="-Isrc/runtime/include" --

            lc tests/array_02.cpp --backend=llvm --extra-arg="-Isrc/runtime/include" --

            lc tests/array_02.cpp --backend=llvm --extra-arg="-Isrc/runtime/include" --

            # Test generating object files
            lc examples/expr2.c --backend c --extra-arg="-Isrc/runtime/include" -o c_o -c --
            lc examples/expr2.c --backend llvm --extra-arg="-Isrc/runtime/include" -o llvm_o -c --
            ls -1

      - name: Test3 (macOS)
        shell: bash -l -e {0}
        if: contains(matrix.os, 'macos')
        run: |
            which clang

            # Test including iostream and span headers
            lc tests/span_01.cpp --ast-dump --ast-dump-file="tests/span_01.ast" --extra-arg="-std=c++20" --
